version: 0.0
os: linux
files:
  - source: checkout-0.0.1-SNAPSHOT.jar
    destination: /var/checkout/
hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
    - location: create_or_update_service.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root